//
//  PLYCodec.swift
//  Export
//
//  Reads and writes the "standard" 3D Gaussian Splatting .ply attribute
//  layout: the one produced by the original INRIA reference implementation
//  and its many descendants (gsplat, Niantic's SPZ tools, PlayCanvas
//  SuperSplat, etc). Verified against the Niantic SPZ project's own
//  saveSplatToPly/loadSplatFromPly (github.com/nianticlabs/spz, MIT
//  licensed, src/cc/load-spz.cc) rather than reconstructed from memory, so
//  the property list and ordering below are byte-for-byte what those tools
//  read and write:
//
//    x y z                                  VEC3 position (RDF convention)
//    nx ny nz                               VEC3 normal (unused; written 0)
//    f_dc_0 f_dc_1 f_dc_2                    raw degree-0 SH coefficient (r,g,b)
//    f_rest_0 .. f_rest_(3*shDim-1)          higher SH coefficients, CHANNEL-MAJOR:
//                                             all R coefficients, then all G, then all B
//    opacity                                pre-sigmoid logit
//    scale_0 scale_1 scale_2                 log-scale
//    rot_0 rot_1 rot_2 rot_3                 quaternion, property order (w, x, y, z)
//
//  Coordinate frame: PLY is RDF (Right, Down, Front); SplatCloud is stored in
//  RUB (see SplatCloud.swift). RUB <-> RDF is a fixed 180-degree rotation
//  about the X axis: negate Y and Z of position, and negate the Y and Z
//  (i.e. "rot_2" and "rot_3") components of the quaternion; X and W are
//  untouched. This does NOT touch spherical harmonics coefficients: the
//  RUB/RDF families share the same "family" bit in SPZ's own
//  CoordinateSystem enum (both are within-family axis flips of X only... of
//  Y/Z only, not a cross-family rotation), and per-coefficient SH rotation
//  is only needed for a true basis rotation, not a pure reflection pair - so
//  this module intentionally does not carry SPZ's general 16-coordinate-
//  system / SH-rotation machinery. TODO(nimbus): if a future need arises to
//  import a .ply authored in some OTHER convention (Unity RUF, Three.js RUB
//  read as-is, etc.), extend this file's coordinate handling rather than
//  silently assuming RDF.
//
//  Only binary_little_endian and ascii PLY are read; binary_big_endian is
//  rejected with a clear error rather than silently misread. Only PLYs whose
//  every vertex property is `float` are accepted - the format in the box
//  above - which covers every Gaussian-splat PLY this app or any known
//  compatible tool produces; a generic colored point cloud (uchar r,g,b) is
//  out of scope and reported as such.
//

import Foundation
import simd

enum PLYCodec {

    // MARK: - Write

    static func write(_ cloud: SplatCloud) throws -> Data {
        guard cloud.count > 0 else { throw ExportError.emptyCloud }
        let n = cloud.count
        let shDim = cloud.shDegree.restCoefficientCount

        var header = "ply\n"
        header += "format binary_little_endian 1.0\n"
        header += "element vertex \(n)\n"
        header += "property float x\nproperty float y\nproperty float z\n"
        header += "property float nx\nproperty float ny\nproperty float nz\n"
        header += "property float f_dc_0\nproperty float f_dc_1\nproperty float f_dc_2\n"
        for i in 0..<(shDim * 3) {
            header += "property float f_rest_\(i)\n"
        }
        header += "property float opacity\n"
        header += "property float scale_0\nproperty float scale_1\nproperty float scale_2\n"
        header += "property float rot_0\nproperty float rot_1\nproperty float rot_2\nproperty float rot_3\n"
        header += "comment generated by \(BrandConfig.productName) \(BrandConfig.versionString)\n"
        header += "end_header\n"

        let floatsPerPoint = 3 + 3 + 3 + shDim * 3 + 1 + 3 + 4
        var body = Data(capacity: n * floatsPerPoint * 4)

        for i in 0..<n {
            let p = cloud.positions[i]
            // RUB -> RDF: negate y, z.
            body.appendFloat32LE(p.x)
            body.appendFloat32LE(-p.y)
            body.appendFloat32LE(-p.z)

            body.appendFloat32LE(0); body.appendFloat32LE(0); body.appendFloat32LE(0)  // normal, unused

            let dc = cloud.colorDC[i]
            body.appendFloat32LE(dc.x); body.appendFloat32LE(dc.y); body.appendFloat32LE(dc.z)

            if shDim > 0 {
                let coeffs = cloud.shRest[i]
                for channel in 0..<3 {
                    for k in 0..<shDim {
                        body.appendFloat32LE(coeffs[k][channel])
                    }
                }
            }

            body.appendFloat32LE(cloud.opacityLogits[i])

            let s = cloud.logScales[i]
            body.appendFloat32LE(s.x); body.appendFloat32LE(s.y); body.appendFloat32LE(s.z)

            // Stored quaternion is (x, y, z, w); RUB -> RDF negates y, z only.
            // A degenerate (zero-length) input would normalize to NaN; fall
            // back to the identity rotation rather than writing NaN floats.
            let rawRotation = cloud.rotations[i]
            let rotLenSq = simd_length_squared(rawRotation)
            let r = simd_normalize(
                (rotLenSq.isFinite && rotLenSq > 1e-12) ? rawRotation : SIMD4<Float>(0, 0, 0, 1)
            )
            // rot_0 = w, rot_1 = x, rot_2 = y (negated), rot_3 = z (negated).
            body.appendFloat32LE(r.w)
            body.appendFloat32LE(r.x)
            body.appendFloat32LE(-r.y)
            body.appendFloat32LE(-r.z)
        }

        var out = Data()
        out.appendASCII(header)
        out.append(body)
        return out
    }

    static func write(_ cloud: SplatCloud, to url: URL) throws {
        let data = try write(cloud)
        do {
            try data.write(to: url, options: .atomic)
        } catch {
            throw ExportError.ioFailure("writing \(url.lastPathComponent): \(error.localizedDescription)")
        }
    }

    // MARK: - Read (import-back)

    static func read(from url: URL) throws -> SplatCloud {
        let data: Data
        do {
            data = try Data(contentsOf: url)
        } catch {
            throw ExportError.ioFailure("reading \(url.lastPathComponent): \(error.localizedDescription)")
        }
        return try read(data)
    }

    static func read(_ data: Data) throws -> SplatCloud {
        var reader = ByteReader(data)

        guard try reader.readLine() == "ply" else {
            throw ExportError.malformedFile("missing 'ply' magic line")
        }

        var isASCII = false
        var vertexCount = 0
        var propertyNames: [String] = []
        var sawFormat = false
        var sawVertexElement = false

        headerLoop: while true {
            let line = try reader.readLine()
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if trimmed == "end_header" { break headerLoop }
            if trimmed.hasPrefix("format ") {
                sawFormat = true
                if trimmed.contains("binary_little_endian") {
                    isASCII = false
                } else if trimmed.contains("ascii") {
                    isASCII = true
                } else {
                    throw ExportError.unsupportedFormat(
                        "PLY format '\(trimmed)' is not supported; only ascii and "
                            + "binary_little_endian are read"
                    )
                }
            } else if trimmed.hasPrefix("element vertex ") {
                sawVertexElement = true
                let countString = trimmed.dropFirst("element vertex ".count)
                guard let count = Int(countString) else {
                    throw ExportError.malformedFile("bad vertex count '\(countString)'")
                }
                vertexCount = count
            } else if trimmed.hasPrefix("element ") {
                // A different, non-vertex element (e.g. "face"). This codec
                // only understands the vertex-only Gaussian-splat layout.
                throw ExportError.unsupportedFormat(
                    "PLY contains a non-vertex element ('\(trimmed)'); only a single "
                        + "'vertex' element with all-float properties is supported"
                )
            } else if trimmed.hasPrefix("property float ") {
                propertyNames.append(String(trimmed.dropFirst("property float ".count)))
            } else if trimmed.hasPrefix("property ") {
                throw ExportError.unsupportedFormat(
                    "PLY has a non-float vertex property ('\(trimmed)'); only "
                        + "Gaussian-splat PLYs with all-float vertex properties are supported"
                )
            }
            // comment / obj_info / other lines are ignored.
        }

        guard sawFormat, sawVertexElement else {
            throw ExportError.malformedFile("PLY header missing format or vertex element")
        }
        guard vertexCount > 0 else { throw ExportError.emptyCloud }

        var index: [String: Int] = [:]
        for (i, name) in propertyNames.enumerated() { index[name] = i }

        func requireIndex(_ name: String) throws -> Int {
            guard let i = index[name] else {
                throw ExportError.malformedFile("PLY is missing required property '\(name)'")
            }
            return i
        }

        let xi = try requireIndex("x"), yi = try requireIndex("y"), zi = try requireIndex("z")
        let dc0 = try requireIndex("f_dc_0"), dc1 = try requireIndex("f_dc_1"), dc2 = try requireIndex("f_dc_2")
        let oi = try requireIndex("opacity")
        let s0 = try requireIndex("scale_0"), s1 = try requireIndex("scale_1"), s2 = try requireIndex("scale_2")
        let r0 = try requireIndex("rot_0"), r1 = try requireIndex("rot_1")
        let r2 = try requireIndex("rot_2"), r3 = try requireIndex("rot_3")

        var shDim = 0
        while index["f_rest_\(shDim * 3)"] != nil { shDim += 1 }
        let shDegree = try shDegreeFor(restCoefficientCount: shDim)
        var restIndices: [Int] = []
        if shDim > 0 {
            restIndices.reserveCapacity(shDim * 3)
            for i in 0..<(shDim * 3) {
                restIndices.append(try requireIndex("f_rest_\(i)"))
            }
        }

        let fieldsPerVertex = propertyNames.count

        // "element vertex N" is plain text in a file this app did not
        // necessarily write, so N is whatever a corrupted or hand-edited byte
        // says it is, and it feeds the array allocation a few lines below. The
        // only check it has had so far is the `vertexCount > 0` guard above.
        // That is not enough, so it is validated twice more before it is
        // believed.
        //
        // First the arithmetic. `vertexCount * fieldsPerVertex` is an Int
        // multiply of two numbers read out of the file, and the `Int(countString)`
        // parse above happily accepts "9223372036854775807", so a single wrong
        // digit in the header overflows that multiply and traps. A trap is not
        // a Swift error, and that distinction matters here specifically:
        // TrainerInitializer.swift line 336 wraps this whole call in
        // `try? PLYCodec.read(from: url)` precisely so that a damaged
        // prepass/init_splats.ply degrades to depth-map seeding instead of
        // taking the scan down, and `try?` catches nothing at all in this case.
        // The same is true of the allocation itself, where a merely large N is
        // answered by the iOS jetsam killer terminating the process rather than
        // by a nil.
        let (totalValues, valueCountOverflowed) =
            vertexCount.multipliedReportingOverflow(by: fieldsPerVertex)
        guard !valueCountOverflowed else {
            throw ExportError.malformedFile(
                "PLY header claims \(vertexCount) vertices of \(fieldsPerVertex) properties "
                    + "each, which is more values than can be counted"
            )
        }

        // Second, cross-check that claim against how much data the file
        // actually still holds, the same way SPZCodec.read already checks its
        // own numPoints against `reader.remaining` before believing it. SPZ
        // needs no overflow guard alongside it because its count is a UInt32;
        // this one does, because a PLY vertex count is an unbounded decimal
        // parse. Without the byte check a header can claim a hundred million
        // vertices inside a four kilobyte file and the reader will allocate for
        // every one of them before discovering, one float at a time, that the
        // body ran out. The reader is parked immediately after "end_header" at
        // this point, because nothing between the header loop and here moves
        // it, so `reader.remaining` is exactly the length of the body.
        //
        // Both bounds below divide the byte count rather than multiplying the
        // value count, so that a bound check cannot overflow in its turn, and
        // both divisors are literals, so that neither can trap on a division by
        // zero if the property checks above are ever reordered. Both are "at
        // least" bounds rather than "exactly" ones, so a trailing newline or
        // other padding after the body stays acceptable the way it was.
        if isASCII {
            // ASCII cannot be predicted exactly, because the same value may be
            // written "0" or "-1.2345678e-09". The floor is still firm: the
            // split below separates on space, tab, CR and LF, so every value
            // costs at least one character of its own and every value but the
            // last costs at least one separator byte after it, which makes N
            // values cost at least 2N-1 bytes. The "+ 1" is load-bearing: it is
            // what keeps the tightest legal body, single-character values one
            // space apart with no trailing newline, from being rejected.
            guard totalValues <= (reader.remaining + 1) / 2 else {
                throw ExportError.malformedFile(
                    "PLY header claims \(vertexCount) vertices of \(fieldsPerVertex) properties, "
                        + "\(totalValues) values, but only \(reader.remaining) bytes of ascii body remain"
                )
            }
        } else {
            // Binary is exact: every value is one little-endian float32, so a
            // body holding this many values cannot be shorter than four bytes
            // per value. A body written by this file's own `write` is exactly
            // that long, so the round-trips in ExportSelfTest sit on the
            // boundary and pass rather than being rejected by one byte.
            guard totalValues <= reader.remaining / 4 else {
                throw ExportError.malformedFile(
                    "PLY header claims \(vertexCount) vertices of \(fieldsPerVertex) properties, "
                        + "\(totalValues) float32 values, but only \(reader.remaining) bytes remain"
                )
            }
        }

        var values = [Float](repeating: 0, count: totalValues)

        if isASCII {
            let rest = String(decoding: reader.bytes[reader.offset...], as: UTF8.self)
            var scanner = rest.split(whereSeparator: { $0 == " " || $0 == "\n" || $0 == "\r" || $0 == "\t" })
                .makeIterator()
            for i in 0..<values.count {
                guard let token = scanner.next(), let v = Float(token) else {
                    throw ExportError.malformedFile("ASCII PLY body ended early at value \(i)")
                }
                values[i] = v
            }
        } else {
            for i in 0..<values.count {
                values[i] = try reader.readFloat32LE()
            }
        }

        var positions = [SIMD3<Float>](); positions.reserveCapacity(vertexCount)
        var rotations = [SIMD4<Float>](); rotations.reserveCapacity(vertexCount)
        var logScales = [SIMD3<Float>](); logScales.reserveCapacity(vertexCount)
        var opacityLogits = [Float](); opacityLogits.reserveCapacity(vertexCount)
        var colorDC = [SIMD3<Float>](); colorDC.reserveCapacity(vertexCount)
        var shRest = [[SIMD3<Float>]](); shRest.reserveCapacity(vertexCount)

        for v in 0..<vertexCount {
            let base = v * fieldsPerVertex
            // RDF -> RUB: negate y, z.
            positions.append(SIMD3(values[base + xi], -values[base + yi], -values[base + zi]))
            colorDC.append(SIMD3(values[base + dc0], values[base + dc1], values[base + dc2]))
            opacityLogits.append(values[base + oi])
            logScales.append(SIMD3(values[base + s0], values[base + s1], values[base + s2]))
            // File order is (w, x, y_rdf, z_rdf); stored order is (x, y, z, w) with y, z negated.
            let w = values[base + r0], x = values[base + r1]
            let yRDF = values[base + r2], zRDF = values[base + r3]
            rotations.append(SIMD4(x, -yRDF, -zRDF, w))

            if shDim > 0 {
                var coeffs = [SIMD3<Float>](); coeffs.reserveCapacity(shDim)
                for k in 0..<shDim {
                    let r = values[base + restIndices[k]]
                    let g = values[base + restIndices[k + shDim]]
                    let b = values[base + restIndices[k + 2 * shDim]]
                    coeffs.append(SIMD3(r, g, b))
                }
                shRest.append(coeffs)
            }
        }

        return try SplatCloud(
            shDegree: shDegree,
            positions: positions,
            rotations: rotations,
            logScales: logScales,
            opacityLogits: opacityLogits,
            colorDC: colorDC,
            shRest: shRest
        )
    }
}

private func shDegreeFor(restCoefficientCount: Int) throws -> SHDegree {
    switch restCoefficientCount {
    case 0: return .zero
    case 3: return .one
    case 8: return .two
    case 15: return .three
    default:
        throw ExportError.malformedFile(
            "PLY has \(restCoefficientCount) f_rest_* properties per vertex, which is not a "
                + "valid Gaussian-splat SH coefficient count (expected 0, 3, 8, or 15)"
        )
    }
}
